### ISSUE TITLE
invisible messages

### ISSUE THREAD

**Issue by gattomarcomix** [rohit-px2/nvui#102]
Hi,
nvui should show an opening message because my vimrc contains an error. The message is invisible.
To understand: this screenshot shows navi and nvim-qt side by side.
[https://pasteboard.co/LO3Wrz4TgOUT.png](url)
Thanks!

**Comment by gattomarcomix** [comment]
![opening](https://user-images.githubusercontent.com/94183109/142840696-3231297e-f93a-45ce-b349-0f05e6529b54.png)

**Comment by gattomarcomix** [comment]
oopppppssss!!

**Comment by rohit-px2** [comment]
Sorry, I don't know why this is happening. Is other text displaying properly (i.e. text color/background is correct)? Also if you type `:messages` into the command line does everything appear properly?

**Comment by gattomarcomix** [comment]
![opening_swap_01](https://user-images.githubusercontent.com/94183109/143411365-82ca9a84-f566-4ce4-9ef0-747619f6f658.png)

another case: swap file is already present.same behavoir

**Comment by gattomarcomix** [comment]
![opening_swap_02](https://user-images.githubusercontent.com/94183109/143411490-58952fd2-25cb-4e1f-a611-bdabe3a8acd9.png)

:messages output seems good .-)

**Comment by gattomarcomix** [comment]
let me know if there are any other tests I can do to help. Thank you!

**Comment by rohit-px2** [comment]
I tested (call invalid function in vimrc) and I'm getting the same issue, I'll see if I can fix it soon

**Comment by rohit-px2** [comment]
I looked into it a while back and what was happening was that nvui was sending resize messages, but Neovim wasn't responding to them while the error message log is open, so this looks like a Neovim problem.
