### ISSUE TITLE
Does not support window opacity on wayland

### ISSUE THREAD

**Issue by gasacchi** [rohit-px2/nvui#108]
nvui does not support window opacity on sway / wayland

install method:
```cmd
yay -S nvui-git
```
nvui config:
```lua
if vim.g.nvui then
   vim.cmd [[NvuiOpacity 0.5]]
end
```
then run nvui with:
```cmd
nvui --ext_multigrid
```
nvui running without transparency

output from terminal:
```log
This plugin does not support setting window opacity
```

**Comment by rohit-px2** [comment]
It looks like Qt doesn't support setting window opacity on Wayland, if you or someone else knows a way to do it e.g. via Wayland API let me know and I can look into it. Otherwise there's not much that can be done.
