### ISSUE TITLE
Error in Linux

### ISSUE THREAD

**Issue by sergiky** [rohit-px2/nvui#110]
Hi guys, when i run this command; 
cmake --build build --target nvui --config Release

i have this error:

![image](https://user-images.githubusercontent.com/90042979/147428395-9e1b623a-c684-44fd-ab33-7668cd034a59.png)

Thanks

**Comment by rohit-px2** [comment]
Oh, my bad, it looks like the macros don't need a semicolon after them. Should be fixed now!
