### ISSUE TITLE
Moving cursor up and down, but it has creeping backward

### ISSUE THREAD

**Issue by axrdiv** [rohit-px2/nvui#111]
Hey guys. Thank you for this awesome project.
When i moving cursor up and down, it has creeping backward.
![output](https://user-images.githubusercontent.com/10485290/147467933-ada48325-8249-46f9-a498-0fff18f38a97.gif)

**Comment by rohit-px2** [comment]
Cursor movement is animated by default. You can disable the movement animation by typing `:NvuiCursorAnimationDuration 0` into the command line.
