### ISSUE TITLE
Cannot customize winsize when startup

### ISSUE THREAD

**Issue by RnYi** [rohit-px2/nvui#113]
I read the doc and found no way to predefine window size. I also tried `set lines=`,  but didn't work.

**Comment by rohit-px2** [comment]
Try `--geometry={rows}x{cols}`, it sets the number of rows and columns it should display, but it can be inaccurate since it's not based on the font you're using in Neovim.

**Comment by rohit-px2** [comment]
I added the `--size` option on master to specify pixel size, so you can do for example `nvui --size=1600x900` to start with a width of 1600 and a height of 900 pixels.
