### ISSUE TITLE
Disable move animation but keep scroll animation.

### ISSUE THREAD

**Issue by DasOhmoff** [rohit-px2/nvui#118]
Hello, thank you for your help.

Nvui offers the option `NvuiAnimationsEnabled`, which enables or disables both scrolling and moving animations. I would like to keep the scrolling animation but disable the moving animation. How can I do so? Also, I would like the moving animation to not be run at all, so that it does not impact the performance.

**Comment by rohit-px2** [comment]
It's not possible on master but I'm working on an improved branch at #117 that allows you to do `:NvuiMoveAnimationDuration 0` to disable the move animation. You can check out the builds [here](https://github.com/rohit-px2/nvui/actions/runs/1674520443). I'm going to merge this in soon (TM)

**Comment by DasOhmoff** [comment]
Ah ok thank you
