### ISSUE TITLE
Mouse often stop work and cause a high CPU usage

### ISSUE THREAD

**Issue by RnYi** [rohit-px2/nvui#120]
If I click with mouse multi times, nvui would not response to mouse anymore, but keyboard still  work well. And I also find a high CPU usage in that scenario.

**Comment by rohit-px2** [comment]
Personally I don't use mouse so I didn't see this, thanks for the report. Should be fixed on the latest commit.

**Comment by RnYi** [comment]
This bug still exists

**Comment by rohit-px2** [comment]
Were you trying with [this build](https://github.com/rohit-px2/nvui/actions/runs/1720974110)? I've been using it for a while and the mouse issues are gone.

**Comment by RnYi** [comment]
> Were you trying with [this build](https://github.com/rohit-px2/nvui/actions/runs/1720974110)? I've been using it for a while and the mouse issues are gone.

yes, it works well up to now!
