### ISSUE TITLE
Remember: Window Position and Size?

### ISSUE THREAD

**Issue by MK-Alias** [rohit-px2/nvui#121]
Hi,

really like this font-end, but is there a way to make the window remember the size and position on the desktop?

Thanks!

**Comment by rohit-px2** [comment]
I've added this in #123, (if builds pass) you can check it out and see if that works for you.

**Comment by MK-Alias** [comment]
Okay, looks nice! You seem to be releasing new versions regularly so will just wait for the next build. But if I get inpatient, i know where to find the source!
