### ISSUE TITLE
frameless title bar leaves big white lines on the other screen when maximized (windows 11)

### ISSUE THREAD

**Issue by kurakurakantor** [rohit-px2/nvui#129]
snapping the app to maximize or clicking the maximize button leaves a white border on the other screen (dual monitor) when using a frameless title bar, no issues if it's disabled. white border doesn't appear if it's snapped on half the screen or quarter, only happens in maximize. also doesn't appear on nvuitogglefullscreen. hopefully could be fixed soon, this is the only customizable title bar nvim gui i could find, and i've been loving it, thank you so much for your hard work.

**Comment by kurakurakantor** [comment]
![image](https://user-images.githubusercontent.com/101485444/158040844-b1e591f9-f1f0-41ca-971a-256c079fa3b1.png)

**Comment by xarthurx** [comment]
I don't have this issue on my machine. But text size is different though.

**Comment by kurakurakantor** [comment]
what os are you onn and what version of nvui are you on?

**Comment by xarthurx** [comment]
Windows 11, newest `nvui`.

**Comment by kurakurakantor** [comment]
huh, weird, is it the newest nvui release or the newest main artifact? could it be that it's just my config? thank you for your reply btw

**Comment by kurakurakantor** [comment]
the white border issue fixes itself if i change the scale of the monitor, but each time i opened a new instance it shows up again, i have no idea what's happening

**Comment by kurakurakantor** [comment]
so uh... like the #133 config size issue... not using showMaximized before the title bar initializes fixes the issue
