### ISSUE TITLE
failed to download from mirrorset

### ISSUE THREAD

**Issue by kurakurakantor** [rohit-px2/nvui#131]
windows compile can't be done because of the failed mirrorset, tried it on my windows, and via github action. i wonder how this could be fixed

Error: Failed to download from mirror set:
https://repo.msys2.org/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404

**Comment by rohit-px2** [comment]
Are you using the steps [here](https://github.com/rohit-px2/nvui/wiki#windows)? If so you shouldn't be using MSYS.

**Comment by rohit-px2** [comment]
Oh, I just realized, it's one of the vcpkg packages failing to build. Not sure what to do about this, I might try and see if updating vcpkg does the trick.

**Comment by kurakurakantor** [comment]
im using github run action to compile HAHA my pc is too messy to setup everything and i don't understand much about programming so im just gonna leave it to your working workflow. also yeah it's vcpkg, i'm trying to manually changing the link and hashes to the ones that are still supported by msys, i have no idea if it'll work tho

**Comment by kurakurakantor** [comment]
manually changing the binutils version and their hashes to a newer supported version in vcpkg_acquire_msys.cmake and vcpkg_find_fortran.cmake solves the issue! i can compile it using windows now
