### ISSUE TITLE
how to save configuration items?

### ISSUE THREAD

**Issue by sangshuduo** [rohit-px2/nvui#137]
sorry for my stupid question.
I am not aware if there is a way to save config items like "set nu" or toggle fullscreen by default like neovim or vim.
How can I compose it somewhere?

**Comment by rohit-px2** [comment]
Just put them as lines in your init.vim
E.g. to open in fullscreen you could just have
`NvuiFullscreen v:true`
in your init.vim, or do `vim.cmd [[NvuiFullscreen v:true]]` for init.lua

**Comment by sangshuduo** [comment]
Cool! Works great. Thanks.

Then I found I have a neovim for windows installed too. It can't recognize NvuiFullscreen config in init.lua. Wonder if I can make both of them works.
