### ISSUE TITLE
[Help] Opening a file using the same instance

### ISSUE THREAD

**Issue by pidgeon777** [rohit-px2/nvui#140]
Hello, I'm looking for a way to externally open a file with `nvui` by making use of the command line.

For example

`nvui.exe -p {pathToTheFile}`

What I would like, is to make use of the already running `nvui` instance, without opening another one.

Is something like that achievable?

**Comment by rohit-px2** [comment]
Unfortunately you can't do that right now in nvui. It might be possible through other GUIs that support remote connection and then using remote Neovim. However, nvui doesn't support that feature.

**Comment by pidgeon777** [comment]
That's a pity, hopefully, one day it'll be supported 👍.
