### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by IndianBoy42** [rohit-px2/nvui#21]
I wanted to try this out, but I get the above error and it doesn't use my font 

my font is `FiraCode Nerd Font:h11`. This works for alacritty/kitty/neovide etc

**Comment by rohit-px2** [comment]
I can reproduce this issue on Ubuntu 20.04.
Can you try setting FONTCONFIG_PATH manually?
e.g. <code>export FONTCONFIG_PATH=/etc/fonts</code>
Also, have you set the font using <code>:set guifont</code>?

**Comment by IndianBoy42** [comment]
with the environment variable set it works, I had `set guifont` already

**Comment by rohit-px2** [comment]
I've added a change to set this environment variable if it hasn't been set, could you check back in 10 minutes and see if the [latest build](https://github.com/rohit-px2/nvui/actions/runs/1180770150) solves your problem?

**Comment by IndianBoy42** [comment]
The latest build works
