### ISSUE TITLE
Can't trigger fcitx

### ISSUE THREAD

**Issue by Avimitin** [rohit-px2/nvui#22]
**My system information**

```text
Linux 5.13.12-arch1-1 x86_64 GNU/Linux
```

**Issue I met**

I am a Chinese user. And I used fcitx as the Chinese input method. However, I can't trigger the input panel like other neovim GUI or the TUI when I am using the nvui.

- Normal behavior in terminal

![image](https://user-images.githubusercontent.com/30021675/131310427-68a5d22e-40ef-4982-bab9-cf10d86095cb.png)

- In nvui

    It just outputs English nor creates the fcitx input panel.

**My fcitx version**:

```text
fcitx version: 4.2.9.7
```

**Comment by rohit-px2** [comment]
This one is a little tough for me since I don't have much experience with Linux or input methods in general. I'll need to dig a little deeper into this.
Does [Neovim-Qt](https://github.com/equalsraf/neovim-qt) work with fcitx?

**Comment by Avimitin** [comment]
> This one is a little tough for me since I don't have much experience with Linux or input methods in general. I'll need to dig a little deeper into this.
> Does [Neovim-Qt](https://github.com/equalsraf/neovim-qt) work with fcitx?

Yes, it works. 

- nvim-qt

![image](https://user-images.githubusercontent.com/30021675/131364422-13cf503d-83ba-4da0-a5c2-cc66b1eb792e.png)

**Comment by rohit-px2** [comment]
I've tried using a Chinese Pinyin input method on Ubuntu and can confirm that the IME display doesn't show.
I'll have to look into this.

**Comment by rohit-px2** [comment]
Hello, can you check if #56 fixes this?

**Comment by Avimitin** [comment]
No, the fcitx panel is still not shown.

**Comment by Avimitin** [comment]
Also, here is my fcitx diagnosis information: https://cfp.vim-cn.com/cb30K. Maybe some input module missing.

**Comment by ouuan** [comment]
My fcitx5 works fine in v0.1.2

**Comment by Avimitin** [comment]
> My fcitx5 works fine in v0.1.2

How do you set your fcitx keymap shortcut? In my machine `<Ctrl+Space>` and `<Ctrl+Shift>` are all not working. The `Ctrl+Space` just act like a normal space input.

**Comment by Avimitin** [comment]
> Also, here is my fcitx diagnosis information: https://cfp.vim-cn.com/cb30K. Maybe some input module missing.

The diagnosis information says "Cannot find fcitx input method module for Qt4". Maybe some Qt4 modules are missing? But  I can trigger the fcitx on nvim-qt, it is weird.

**Comment by ouuan** [comment]
> How do you set your fcitx keymap shortcut?

Ctrl+Space

**Comment by Avimitin** [comment]
May I ask how your fcitx environment variables are set?

**Comment by ouuan** [comment]
> May I ask how your fcitx environment variables are set?

```
GTK_IM_MODULE=fcitx5
INPUT_METHOD=fcitx5
QT_IM_MODULE=fcitx5
XMODIFIERS=@im=fcitx5
```

**Comment by Avimitin** [comment]
Same environment variable setting. So it's not related to it.

**Comment by Avimitin** [comment]
I think I found out the problem. For people who have trouble like me: you need to compile it at local, the binary in action is not compatible with fcitx.
