### ISSUE TITLE
Launch frameless 

### ISSUE THREAD

**Issue by IndianBoy42** [rohit-px2/nvui#24]
How can I make nvui always launch frameless? I was thinking run `:NvimFrameless v:false` in my init.lua (btw its a bit confusing that `frameless false` will hide the titlebar (making it frameless), maybe it shouldbe `NvuiTitlebar v:false` or `NvuiFrameless v:true` to hide the titlebar). 

But I think a better solution would be a command line argument

**Comment by rohit-px2** [comment]
Yeah, nvui doesn't offer the ability to have absolutely no frame right now. You can hide the title bar if you go into fullscreen mode (<code>:NvuiFullscreen v:true</code>).

What <code>:NvuiFrameless</code> does is switch between the custom title bar and the native title bar. The custom title bar is achieved by setting a frameless window (absolutely no frame), and then showing a custom title bar widget, as well as handling moving and resizing within the program as opposed to letting the windowing system deal with it.

If you want a completely frameless window, it's possible but there wouldn't be any window controls so once the window shows up there would be nothing you could do with it. (Unless you call :NvuiFrameless,).

**Comment by ouuan** [comment]
> What `:NvuiFrameless` does is switch between the custom title bar and the native title bar. The custom title bar is achieved by setting a frameless window (absolutely no frame), and then showing a custom title bar widget, as well as handling moving and resizing within the program as opposed to letting the windowing system deal with it.

It's very confusing to call the command "NvuiFrameless" only because you set the frameless window hint in the code. It's "frameless" for Qt/window manager, but not for users. I suggest changing the name of the command.

**Comment by ouuan** [comment]
BTW, the reply doesn't answer the issue. It only explains why "NvuiFrameless" is not frameless, which answers the "btw". But it doesn't offer a method to launch NVUI with `:NvimFrameless v:false`.

**Comment by ouuan** [comment]
And I think it's not a good idea to enable the custom title bar by default.

**Comment by rohit-px2** [comment]
Yeah, I had a discussion a little earlier to use the native title bar and it's been planned, but I have been away/busy for the past few days.
