### ISSUE TITLE
--ext_popupmenu overlaps with documentation popups of nvim-cmp

### ISSUE THREAD

**Issue by IndianBoy42** [rohit-px2/nvui#25]
NVui:
![image](https://user-images.githubusercontent.com/5981889/131318029-ee30fcc3-2021-4af7-9704-3d8b953ccc78.png)

Terminal: 
![image](https://user-images.githubusercontent.com/5981889/131318097-74da2683-1e63-433a-8ee0-ef236a2bf18b.png)

Is there anyway to fix this?

**Comment by rohit-px2** [comment]
Yeah, I've noticed this quite recently. I think this is a problem with Neovim, since the documentation popup shouldn't even be showing when the <code>ext_popupmenu</code> flag is set.

**Comment by rohit-px2** [comment]
Update: There is a workaround (any floating window that is created while the popup menu is active is aligned to the popup menu) which I've added in #68. The workaround requires `ext_multigrid` so for it to work you need to have started nvui with `--ext_multigrid` flag.
