### ISSUE TITLE
--ext_cmdline is incompatible with wilder.nvim

### ISSUE THREAD

**Issue by IndianBoy42** [rohit-px2/nvui#26]
https://github.com/gelguy/wilder.nvim

wilder.nvim is a plugin for better fuzzy autocompletion for the commandline. with `--ext_cmdline`, the command line moves up, but the popupmenu still stays down. I wonder if a custom renderer for wilder.nvim could be written to show the autocompletions below the external commandline

**Comment by rohit-px2** [comment]
Neovim controls the popup menu, so unless nvui is receiving `popupmenu_show` events, it won't display the popup menu. I believe this would be something that Neovim itself has to support.
