### ISSUE TITLE
Weird font issue

### ISSUE THREAD

**Issue by ahmedkhalf** [rohit-px2/nvui#28]
I don't have a config, just stock nvim.

![image](https://user-images.githubusercontent.com/36672196/131337622-d92a8ba6-9d24-4621-89db-eb146eabf82c.png)

Platform: Manjaro Linux

**Comment by rohit-px2** [comment]
That should be because no font is set, a random font is chosen, which is most likely not monspace and ends up breaking the text rendering. Could you try setting the <code>guifont<code>? E.g. <code>set guifont=Monospace:h11</code>.

In the future, nvui should use some default monospace font if the guifont has not been set yet.

**Comment by rohit-px2** [comment]
Does #33 solve your problem?

**Comment by ahmedkhalf** [comment]
Fixed, but there is still some weird issue where there is no sync between cursor and text? Perhaps the font is not monospaced?

https://user-images.githubusercontent.com/36672196/131458256-2f0d437f-2aea-43a4-9852-3fa49df974e1.mp4

**Comment by rohit-px2** [comment]
The cursor is an animation which is on by default, you can disable it through the command `:NvuiCursorFrametime -1`. See `:h nvui-cursor` for more info

The clipping shouldn't be happening, I'll have to look into that.

**Comment by ahmedkhalf** [comment]
Yep thats right, basically it's some kind of sizing issue, as seen here:

![image](https://user-images.githubusercontent.com/36672196/131524629-b8d94d41-54a6-43a0-b02b-fbd7144ae86c.png)

**Comment by en1tan** [comment]
I am still experiencing this

**Comment by rohit-px2** [comment]
Hey! Sorry for the late update but I am trying to fix these issues on the branch #68. This branch also has fixes for keyboard input on macOS. Please let me know if you are still experiencing issues using this branch, there are releases [here](https://github.com/rohit-px2/nvui/actions/runs/1275790332).
