### ISSUE TITLE
Use native frame

### ISSUE THREAD

**Issue by ahmedkhalf** [rohit-px2/nvui#29]
On i3wm Linux, nvui launches with this frame:

![image](https://user-images.githubusercontent.com/36672196/131337802-58d9181b-33c5-4e1b-b160-5f797a75d16e.png)

I want it to launch with the regular/native i3 frame.

![image](https://user-images.githubusercontent.com/36672196/131337992-df7bc761-2b89-4970-8be9-11bc7d30ca6c.png)

**Comment by rohit-px2** [comment]
Have you tried <code>:NvuiFrameless v:false</code>?

**Comment by ahmedkhalf** [comment]
Fixed, thank you!
