### ISSUE TITLE
Render/Font Issue 

### ISSUE THREAD

**Issue by Marenz** [rohit-px2/nvui#32]
This is basically with no configuration, just starting it..

https://user-images.githubusercontent.com/424752/131359631-b77bc773-14c8-4b1d-bb6a-9f09e94aebea.mp4

**Comment by Marenz** [comment]
Oh, for context: I did start a terminal using `:term` here. Then I just pressed the right-key.

**Comment by rohit-px2** [comment]
Did you `:set guifont` to a monospace font?
This should be problem where a default monospace font is not set. nvui uses Qt's default font which isn't monospace and doesn't work well with the text rendering. This should be related to #28. 
A solution would be what Neovim-Qt etc. do, which is start with a default monospace font set (Courier New on Mac, Monospace on Linux, and Consolas on Windows)

**Comment by Marenz** [comment]
Setting guifont does the trick indeed!

**Comment by rohit-px2** [comment]
Great :)
