### ISSUE TITLE
Can't use " to access registers and can't type special characteres like ç ..

### ISSUE THREAD

**Issue by lbiaggi** [rohit-px2/nvui#34]
Hello, this Ui looks promising, but I can't access my registers or type ç,ã,õ... inside nvui

**Comment by rohit-px2** [comment]
Hi! I need to diagnose this problem a little more, could you tell me your
- Operating System
- Keyboard Layout / Language

Also, by "can't access my registers", do you mean that it is not typing characters like the double quote (")? If so, when you try and type these characters what text is it displaying as?

**Comment by lbiaggi** [comment]
my bad
OS: Linux

Keyboard conf:
❯ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us
variant:    intl

> Also, by "can't access my registers", do you mean that it is not typing characters like the double quote (")? If so, when you try and type these characters what text is it displaying as? 

Nothing, it just ignores it

https://user-images.githubusercontent.com/5401584/131389495-c9294a26-d8fb-465a-bfc2-e6db6f904c3b.mp4

**Comment by rohit-px2** [comment]
Hey, sorry for the late update. I think that #68 might fix your problem. Builds are [here](https://github.com/rohit-px2/nvui/actions/runs/1283210836). Let me know if you are still experiencing issues.
