### ISSUE TITLE
crash after running an output-heavy process in the terminal

### ISSUE THREAD

**Issue by Marenz** [rohit-px2/nvui#41]
When opening a terminal (using `:term`) and running an output-heavy application, after a while nvui crashes. 
The terminal where i started it from then says:

```
terminate called after throwing an instance of 'msgpack::v1::insufficient_bytes'
  what():  insufficient bytes

abort (core dumped)
```

**Comment by Marenz** [comment]
I can make a debug version with more information if required...

**Comment by rohit-px2** [comment]
Could you check and see if #42 solves this problem?

**Comment by Marenz** [comment]
Still crashes, though this time with:
```
terminate called after throwing an instance of 'boost::process::process_error'
  what():  Bad address

[1]  + 63906 abort (core dumped)  ~/Projects/nvui/build/nvui .
```

**Comment by rohit-px2** [comment]
Odd, I guess read or writing is throwing an exception.
Are you typing / doing anything when it crashes or does it crash without any interaction?

Also what platform are you on?

**Comment by rohit-px2** [comment]
Ok, I can reproduce the error now.
Ubuntu 20.04, `nvui --ext_multigrid`
Steps:
1. Put a bunch (>15) of LARGE (>1MB) text files in one directory
2. `cat *.txt`
3. After some time nvui crashes

**Comment by Marenz** [comment]
No typing or any interaction. I triggered it using
```
while true; do find .; done
```

I am also on ubuntu 20.04

**Comment by rohit-px2** [comment]
Ok, now #42 should work.
