### ISSUE TITLE
How to run nvim with specific arguments?

### ISSUE THREAD

**Issue by ahmedkhalf** [rohit-px2/nvui#43]
This might be a nood question, but right now im trying to run nvui with those arguments:
```
nvim -u ~/.local/share/lunarvim/lvim/init.lua
```
and it doesn't work. How to pass arguments to neovim?

**Comment by rohit-px2** [comment]
You can forward arguments to Neovim using the `--` flag, Neovim-Qt style.
So in your case it would be `nvui -- -u ~/.local/share/lunarvim/lvim/init.lua`.
You can also specify the `nvim` to use using `--nvim=/path/to/nvim` e.g. `nvui --nvim=/usr/local/bin/lvim` (that's where my Lunarvim installation is on Ubuntu).

**Comment by ahmedkhalf** [comment]
nice! tnx
