### ISSUE TITLE
nvui doesn't render all nerd fonts

### ISSUE THREAD

**Issue by ahmedkhalf** [rohit-px2/nvui#44]
![image](https://user-images.githubusercontent.com/36672196/131525066-1fef666e-3ee9-416a-a1b8-240a36d06610.png)

As you can see, it renders some, but it doesn't render all.

Font: 
![image](https://user-images.githubusercontent.com/36672196/131525250-5a63f4ed-7e91-46fd-a12e-6ff7a6162928.png)

**Comment by rohit-px2** [comment]
Weird. Could you try with another nerd font and see if it works? For example, I tried FiraCode Nerd Font and it works.
Can you also try setting another Nerd Font as a fallback font and see if the characters render properly?
