### ISSUE TITLE
Rendering issues: command line renders below screen

### ISSUE THREAD

**Issue by rabirabirara** [rohit-px2/nvui#46]
![image](https://user-images.githubusercontent.com/59306451/131557950-0d80c0c9-581e-4799-9941-cebe3a7b168c.png)

Just off the bat, this is what `nvui` looks like when I open it.  

For starters, it's confused by my taskbar placement and hides the title bar behind it; this is remedied by using the Windows+Arrow keys of course.

Secondly, the correct font is not used; it renders a non-monospaced font.  I have a ginit.vim, but nvui hasn't read any of it.  How do I get it to read my configuration?  I know that the problem stems from not having a monospace font (#32), but I've set a monospace font in configuration.

Speaking of setting, for some reason I can't see the status line no matter what.  This means I can't see commands; they are below the window.

https://user-images.githubusercontent.com/59306451/131559040-37f2f269-a1ae-4f9f-81fa-ef496258d0b0.mp4

(Sorry about the recording; I just used the Powerpoint screen recorder.  I captured the entirety of the nvui screen for sure.)

Now, I can set guifont to some fallback like Consolas after I get into the gui.  And I'm sure I could set the window to open to whatever position I want it (just need to figure out where to configure it, or use the terminal).  However, I still wouldn't be able to see the command line.  Do you have any idea why this occurs?  It occurs even with `init.vim` and `ginit.vim` empty.

I am on Windows 10, with neovim 0.5.0.

**Comment by rohit-px2** [comment]
nvui doesn't read the `ginit.vim`. Instead nvui defines the variable `g:nvui`, so you can place nvui configuration commands like this.

`init.vim`
```vim
if exists('g:nvui')
  " configure nvui here (ex.)
  NvuiCmdFontFamily Jetbrains Mono
  set guifont=Consolas
endif
```

`init.lua`
```lua
if vim.fn.exists('g:nvui') ~= 0 then
  -- Configure nvui here
end
```

Just as an example, here's a snippet of what my nvui config looks like:
```vim
if exists('g:nvui')
  set linespace=1
  set guifont=Consolas\ NF:h11
  NvuiPopupMenuDefaultIconFg white
  NvuiCmdBg #1e2125
  NvuiCmdFg #abb2bf
  NvuiCmdBigFontScaleFactor 1.0
  NvuiCmdPadding 10
  NvuiCmdCenterXPos 0.5
  NvuiCmdTopPos 0.0
  NvuiCmdFontFamily Fantasque Sans Mono
  NvuiCmdFontSize 25.0
  NvuiCmdBorderWidth 5
  NvuiPopupMenuIconFg variable #56b6c2
  NvuiPopupMenuIconFg function #c678dd
  NvuiPopupMenuIconFg method #c678dd
  NvuiPopupMenuIconFg field #d19a66
  NvuiPopupMenuIconFg property #d19a66
  NvuiPopupMenuIconFg module white
  NvuiPopupMenuIconFg struct #e5c07b
  NvuiCaretExtendTop 15
  NvuiCaretExtendBottom 8
  NvuiTitlebarFontSize 12
  NvuiTitlebarFontFamily Arial
  NvuiCursorAnimationDuration 0.1
  set guicursor=n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor-blinkwait300-blinkon500-blinkoff300,r-cr-o:hor20
endif
```
I would have to look into the command line showing problem. Could you disable the frameless window (`:NvuiFrameless v:false`) and see if that solves anything?

**Comment by rabirabirara** [comment]
Thanks for the response.  Unfortunately, it doesn't solve the command line from hiding underneath the screen.  I did however stumble upon some new information - it's not a problem solely with the command line, but rather the entire bottom few lines of the GUI window are simply not rendered.  If I open a buffer, I can move the cursor down, and it will go out of the screen as though it's still in the window - but the program window itself does not render it, and changing its size does not help.

A little demonstration.  (Again, apologies for the messiness.)

https://user-images.githubusercontent.com/59306451/131614665-a3c25164-4151-403b-85ce-3363879b06ee.mp4

**Comment by hosxy** [comment]
I also have this problem on Windows 10 (version 2004)

**Comment by rohit-px2** [comment]
So for those bottom lines there is no text?
At the bottom of the window is there any background color or is it just black?

**Comment by rohit-px2** [comment]
Could you check if #65 fixes your issues? If you had a non standard (i.e. not 100%) DPI setting the problem may have been caused by that.

**Comment by hosxy** [comment]
> 
> 
> Could you check if #65 fixes your issues? If you had a non standard (i.e. not 100%) DPI setting the problem may have been caused by that.

yeah，my DPI is 125% and this solve my problem. Now I can see command line.

**Comment by rabirabirara** [comment]
Yup, problem solved. Good work!

![image](https://user-images.githubusercontent.com/59306451/133309671-5250c114-d7b9-4e23-998e-863dc1e051c0.png)
