### ISSUE TITLE
Nvui crashes after a second

### ISSUE THREAD

**Issue by paulkoeckdev** [rohit-px2/nvui#49]
I downloaded the zip file and extracted it into a separate folder. When running bin/nvui, a black window pops up which closes itself after a second.

When running from the terminal, I get this output: 
```
./nvui
terminate called after throwing an instance of 'msgpack::v1::type_error'
  what():  std::bad_cast
fish: “./nvui” terminated by signal SIGABRT (Abort)
```
I am running Pop!_OS 21.04 x86_64.

**Thanks!**

**Comment by Marenz** [comment]
I have the same output with the latest `main` branch version. However it doesn't happen "after a second" for me but after I did a lot of output on the terminal once again


```
terminate called after throwing an instance of 'msgpack::v1::type_error'
  what():  std::bad_cast

[1]  + 10711 abort (core dumped)  ~/Projects/nvui/build/nvui .

```

**Comment by rohit-px2** [comment]
Could you try running with `--ext_hlstate=false` and see if that works?

**Comment by paulkoeckdev** [comment]
> Could you try running with `--ext_hlstate=false` and see if that works?

This fixed the problem, thanks!

**Comment by rohit-px2** [comment]
@Marenz does this fix your issue as well?
