### ISSUE TITLE
kdheepak/lazygit.nvim does not show whne nvui is opened with --ext__multigrid

### ISSUE THREAD

**Issue by parascent** [rohit-px2/nvui#50]
The contents of lazygit are not shown. But the outline is shown.
Plugins like telescope work perfectly.

**Comment by rohit-px2** [comment]
Which platform are you on?
Also when you run nvui, can you pass `--ext_hlstate=false` as an argument and see if that works?

**Comment by parascent** [comment]
I am on Manjaro. 
Doesnt work with `--ext_hlstate=false` either.

**Comment by rohit-px2** [comment]
Okay, I can reproduce this.

**Comment by rohit-px2** [comment]
So it looks like this is a problem with the z-indexing system, the text is drawn to the appropriate grid, but it is not shown. There is actually another grid which draws the outline and it looks like that one is being drawn after the grid with the LazyGit text, which causes the LazyGit window to look blank.

**Comment by rohit-px2** [comment]
Took a super long time but I think I finally managed to fix this on #103
