### ISSUE TITLE
Crashes with error message 

### ISSUE THREAD

**Issue by parascent** [rohit-px2/nvui#51]
Platform:- Manjaro
NVUI run command:-` nvui  --ext_cmdline --ext_multigrid --ext_hlstate=false`
Built NVUI commit:- `commit 5acbe5b85a70662e70ab12cd17a9b81c8b7142ae (HEAD -> exception_insufficient_bytes)`
Just happened while using the app. Did not notice that I was doing anything significant at the time.
```
terminate called after throwing an instance of 'boost::process::process_error'
  what():  Bad address
[1]    4161628 abort (core dumped)  ./nvui --ext_cmdline --ext_multigrid --ext_hlstate=false
```

**Comment by rohit-px2** [comment]
That commit had an issue, should be fixed in release v0.1.1 (see the "Releases" tab).
