### ISSUE TITLE
Crashes with error message "what():  std::bad_cast"

### ISSUE THREAD

**Issue by shampee** [rohit-px2/nvui#52]
Upon running the 0.1.1 release linux-x64 binary, a window is created but it promptly crashes with the message:
```
terminate called after throwing an instance of 'msgpack::v1::type_error'
  what():  std::bad_cast
Aborted (core dumped)
```
I ran `valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all` on it: [valgrind.log](https://github.com/rohit-px2/nvui/files/7107891/valgrind.log)

Here's an additional thing valgrind that weren't included in the log:
```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
```

**Comment by shampee** [comment]
It's worth noting it runs with `nvui --ext_cmdline --ext_multigrid --ext_hlstate=false`

**Comment by rohit-px2** [comment]
Yeah, I think it's a problem with `ext_hlstate`. It's used for the popup menu but nothing else, so I might just disable it by default and offer some other way to change the popup menu colours (like commands).

**Comment by rohit-px2** [comment]
Worth noting that #49 had the same problem when opening Chadtree.

**Comment by rohit-px2** [comment]
Actually I don't think the popup menu depends on `ext_hlstate`, I guess I'll just disable it by default then

**Comment by rohit-px2** [comment]
The latest build on the main branch should fix this issue, you can find the action builds [here](https://github.com/rohit-px2/nvui/actions/runs/1200171580)

**Comment by rohit-px2** [comment]
v0.1.2 now has `ext_hlstate` disabled by default, I'll mark this as closed.
