### ISSUE TITLE
 Square brackets and curly brackets  Italian Keyboard not work

### ISSUE THREAD

**Issue by sphynx79** [rohit-px2/nvui#54]
Thanks for your amazing application.

When i try to insert  Square brackets in insert mode (Italian keyboard), i press [AltGr è] to insert [ and [AltGr +] to insert ]

But not work same problem  for curly brackets that a press [ctrl-alt-shift è] and [ctrl-alt-shift +]

**Comment by rohit-px2** [comment]
Yeah, I can reproduce this on Windows 10 with Italian keyboard as well. The key press event code needs some work to handle different languages.

**Comment by rohit-px2** [comment]
Could you check if [this branch](https://github.com/rohit-px2/nvui/tree/win_altgr) solves your issue? (Actions [here](https://github.com/rohit-px2/nvui/actions/runs/1201331275))

**Comment by sphynx79** [comment]
yes with this branch work nice, can you merge to master?

How i can check in my init.lua if i use Nvui, for example in Neovide i use vim.g.neovide in gonvim i use vim.g.gonvim_running

Thanks

**Comment by rohit-px2** [comment]
Yep, I'll merge it into master now.
You can check if nvui is running using `g:nvui` in VimL or `vim.g.nvui` in Lua.
