### ISSUE TITLE
Check if running inside nvui

### ISSUE THREAD

**Issue by drdilyor** [rohit-px2/nvui#60]
Sorry for such a dumb question but:

How to check if my .vimrc is executed by nvui? `has('gui_running')` returns 0. Also tried searching (`/`) help for `check` but didn't found anything.

**Comment by rohit-px2** [comment]
You can check if nvui is running through `g:nvui`, see [the wiki](https://github.com/rohit-px2/nvui/wiki#configuration-in-vim)
