### ISSUE TITLE
Cursor jumps when resizing or moving

### ISSUE THREAD

**Issue by drdilyor** [rohit-px2/nvui#61]
Huge thanks for a quick response and an amazing app, but there seems to be a little usability problem. Cursor jumps to top left when moving. Window width/height becomes 2x when resizing from right or bottom. No problem when using win button.

https://user-images.githubusercontent.com/62857168/132721898-0808383d-e091-4858-8fd5-cd39acc4d03b.mp4

Distro: arch
Desktop: KDE
WM: KWin
Binary Source: GitHub releases (couldn't build: cmake's taking forever)

No problem when using win button.

**Comment by rohit-px2** [comment]
Yeah the frameless window controls are pretty messed up on Linux / Mac it seems. For the frameless window, the underlying logic is using Qt's functions so theres unfortunately not much I can do about it for now.
You can turn off the frameless window using `:NvuiFrameless v:false` which will go back to using a native window and resizing and moving should work as normal.

**Comment by rohit-px2** [comment]
nvui now uses the native title bar as default which definitely should not have this issue, so I will close this now.
