### ISSUE TITLE
Trouble building on Windows

### ISSUE THREAD

**Issue by dustinroepsch** [rohit-px2/nvui#62]
When I follow the windows build instructions, I see the following error message: 

```
PS C:\Users\duryanro\nvui> cmake -B build . -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja
CMake Error at CMakeLists.txt:37 (find_package):
  Could not find a package configuration file provided by "msgpack" with any
  of the following names:

    msgpackConfig.cmake
    msgpack-config.cmake

  Add the installation prefix of "msgpack" to CMAKE_PREFIX_PATH or set
  "msgpack_DIR" to a directory containing one of the above files.  If
  "msgpack" provides a separate development package or SDK, be sure it has
  been installed.
  ```
  
  It's my understanding that vcpkg should handle installing dependencies like msgpack for me - are the build instructions missing a step? 
  
  I have the vcpkg git submodule cloned (I cloned nvui with recursive submodules like the instructions say) 
  
  Thanks! Excited to see how this compares to Neovide, once I can get it building :)

**Comment by rohit-px2** [comment]
Try using `cmd` for that step, I was having that problem using powershell.

**Comment by rohit-px2** [comment]
Also beware, it takes a long time to build mainly because of Qt.

**Comment by dustinroepsch** [comment]
I get the same error message if I use `cmd` instead of `powershell`

**Comment by rohit-px2** [comment]
That's weird. Did you clear the CMake files from the build folder before trying again using `cmd`?

**Comment by dustinroepsch** [comment]
Deleting the cache helped, thanks!
