### ISSUE TITLE
Resize didn't work

### ISSUE THREAD

**Issue by en1tan** [rohit-px2/nvui#63]
### Steps to achieve this
Followed the build steps in [the wiki](https://github.com/rohit-px2/nvui/wiki)
When snapping to the edge of the screen, it maintains its size, and when trying to resize using the edges, no luck either except the log in the terminal.
![image](https://user-images.githubusercontent.com/16443589/132997149-5a487aa1-7d32-4f6f-a80c-7ba9eef4ede2.png)

On MacOS

**Comment by rohit-px2** [comment]
It looks like mac doesn't support Qt's `QWindow::startSystemResize` method, so the native title bar should be used.
Soon (probably today/tomorrow) I'll make a change to nvui's default behaviour to use the native title bar instead of the custom title bar.

**Comment by en1tan** [comment]
alright then
