### ISSUE TITLE
[Question] how to use `<Ctrl-` or `<D-` key 

### ISSUE THREAD

**Issue by ray-x** [rohit-px2/nvui#69]
Not sure if those keys were remapped. 
By default \<CTRL-R>* will paste from register`*` But it does not seem to be working.
Also in mac \<Command> key (WIN key in windows) does not work.
Are there anything missing from default config in MacOS?

**Comment by rohit-px2** [comment]
Could you try the branch #68 and see if it fixes this issue?

**Comment by ray-x** [comment]
not yet... Is there config flag I need to set?

**Comment by rohit-px2** [comment]
Sorry, there's no config flag, it looks like there's still some deficiencies in keyboard input on Mac. I haven't been able to fix these issues because I don't have a Mac on hand to test. I'm trying to fix this keyboard issue as well as issue #70 in the #68 branch, but it's a work in progress.

**Comment by rohit-px2** [comment]
@ray-x I believe the newest commit on #68 should fix this issue.

**Comment by ray-x** [comment]
I downloaded the branch build.
\<CMD-> is working now and mapped to \<D-> in mac. Thanks!
But \<Ctrl-> does not work correctly.   e.g.  Seems \<C-R> mapped to \<D-R> in my mac.

**Comment by rohit-px2** [comment]
Actually the Cmd key should be mapping to <C-> and the Control key should map to <D-> on Mac.
Which mac version are you running?

**Comment by ray-x** [comment]
Ok. It may be caused by my re-map then.
My mac version 10.15.7

**Comment by rohit-px2** [comment]
Probably isn't caused by your remap, most likely it's an issue with the changes. The problem is mainly with Qt since the method for converting input to a string (QKeyEvent::text) is returning an empty string when these modifiers are pressed on Mac, so we have to work around it with some hacks.

**Comment by ray-x** [comment]
I would suggest having a dedicated cmd/win key in send_input function

**Comment by rohit-px2** [comment]
I've replaced the key processing code with Neovim-Qt's with some slight modifications, let me know how it works for you.
Builds are [here](https://github.com/rohit-px2/nvui/actions/runs/1283210836).

**Comment by rohit-px2** [comment]
The `Ctrl` key is supposed to do that on Mac, it acts as the Super/`<D-` key since `Cmd` maps to `<C-` key. Is the `Cmd` key mapping to `<C-`?

**Comment by ray-x** [comment]
I am a bit confused. 
In gui nvim application
`<C-r>`
`<D-r>`
`<M-r>`
Are different keybinding

**Comment by rohit-px2** [comment]
Yes they are. On mac to use these keybindings the keys you would press are:
`<C-r>`: Cmd+r
`<D-r>`: Ctrl+r
`<M-r>`: Alt+r
Whereas on other platforms it looks like this:
`<C-r>`: Ctrl+r
`<D-r>`: Super/Win+r
`<M-r>`: Alt+r
See the `Ctrl` key on the keyboard indicates a different key binding based on the OS.

**Comment by ray-x** [comment]
Not really, should look like this:
```
<C-r>: Ctrl+r
<D-r>: CMD+r
<M-r>: Alt+r
```
The behavior should be similar to nvim-qt/goneovim

**Comment by rohit-px2** [comment]
Didn't realize that was how it was on Mac. I've pushed a change to swap around the modifiers. Actions are still building but you can find them [here](https://github.com/rohit-px2/nvui/actions/runs/1285294813), let me know how it works.

**Comment by ray-x** [comment]
I think it works now.
