### ISSUE TITLE
Spacing issues on macOS

### ISSUE THREAD

**Issue by bmulholland** [rohit-px2/nvui#70]
There are weird blank spots and alignment issues on macOS that I haven't seen using the same config on different (G)UIs:

Near the end of a line: there's text not showing, as you can see where my cursor is:
<img width="129" alt="Screen Shot 2021-09-22 at 15 49 07" src="https://user-images.githubusercontent.com/247713/134356058-e4039ee4-df40-4bcf-b78e-a1e5f7816dce.png">

Here there are weird spaces before the `::` chars:
<img width="271" alt="Screen Shot 2021-09-22 at 15 50 14" src="https://user-images.githubusercontent.com/247713/134356242-28beadc8-29e5-4d22-a4ed-e34170470e60.png">

Here there's one space before and after the = sign. Also, the word actually reads "URL" and the cursor is on the R - but it's overlapping the L, so you see two R's.
<img width="331" alt="Screen Shot 2021-09-22 at 15 50 58" src="https://user-images.githubusercontent.com/247713/134356370-8c16459a-f3ad-4cea-bfa0-6388e5815807.png">

And here's the telescope UI:
<img width="1031" alt="Screen Shot 2021-09-22 at 15 52 44" src="https://user-images.githubusercontent.com/247713/134356676-8cd697c6-1823-4970-8f5f-ebd188cc0e2f.png">

**Comment by rohit-px2** [comment]
Yeah that doesn't look right. I think it might (potentially) be that the font width is bigger than nvui has calculated it?
Some questions:
- What's your guifont setting?
- If you switch to a different font or raise/lower the font size, are these issues still there?

**Comment by bmulholland** [comment]
guifont is VictorMono Nerd Font. It has ligatures so maybe that's the problem?
 
Don't have time to test different fonts or sizes right now, will report back later.

**Comment by rohit-px2** [comment]
Ligatures shouldn't be the problem.
Could you try building #68 and seeing if that fixes it?

**Comment by rohit-px2** [comment]
Actually I think it might be the font. I just installed Victor Mono Nerd Font on Windows and those graphical glitches are showing up for me. Victor Mono (non-nerd font) works perfectly fine though.
I'll try to fix this. In the meantime, if other fonts are working, you can try defining a fallback font e.g.
`set guifont=Victor\ Mono,FiraCode\ NF` for nerd font fallback.

**Comment by bmulholland** [comment]
Thanks for the workaround. I'm evaluating other GUIs now, will come back around to nvui later :)
