### ISSUE TITLE
Crashes when opening help doc (:h nvui-*)

### ISSUE THREAD

**Issue by tekpriest** [rohit-px2/nvui#72]
OS: MacOS
Latest Release

I ran the executable with this commands `--ext_multigrid --ext_popupmenu --ext_hlstate` but when I try the `:h nvui-titlebar` it crashes
Screenshot
![2021-09-27_01-17-33](https://user-images.githubusercontent.com/16443589/134829365-138ae608-eeca-43ea-930c-adc37d7a98bd.png)

**Comment by en1tan** [comment]
turns out same error occurs without any flags passed
here's the config for nvui in my lua file
```
-- This config here is for nvui
if vim.g.nvui then
-- Set gui font
  cmd [[set guifont=FiraCode\ Nerd\ Font:h9]]
  cmd [[NvuiCmdFontFamily FiraCode Nerd Font]]
  cmd [[NvuiCmdFontSize 9.0]]
  cmd [[NvuiScrollAnimationDuration 0.2]]
end
```

**Comment by rohit-px2** [comment]
Thanks for the report. Which branch are you using? Also, does it crash on startup or when you specifically do some action?

**Comment by en1tan** [comment]
using this branch https://github.com/rohit-px2/nvui/actions/runs/1275790332
when I run the environment and use the help manpage `:h nvui-titlebar`

**Comment by rohit-px2** [comment]
Try not running with `--ext_hlstate`. I disabled this feature because people were getting crashes, and it doesn't affect anything in the editor.

**Comment by en1tan** [comment]
lemme try that

**Comment by en1tan** [comment]
same crashing, no flags passed this time around

**Comment by rohit-px2** [comment]
Okay. Does opening any other window/file cause a crash or is it just the vim doc?
Unfortunately I can't reproduce this. I'll keep this issue open.
I'm planning to add logging capabilities to nvui soon (tracing, errors, etc.) so that might help with figuring out what the problem is.

**Comment by en1tan** [comment]
only when checking nvui doc, any other vim/nvim doc works as intended

**Comment by rohit-px2** [comment]
How about any project with multiple splits?
That is very odd, there shouldn't be any difference in behaviour when it comes to opening files.

**Comment by en1tan** [comment]
open multiple splits no problems, only when trying to access nvui doc with `:h nvui-*`
Opening files/folders is no issue

**Comment by rohit-px2** [comment]
Okay, then there might be something wrong with the help doc.
Which version of Neovim are you using? If you are using nightly could you try on a stable version and see if it crashes? You can the path to the nvim executable using `nvui --nvim=/path/to/nvim`.

**Comment by en1tan** [comment]
nvim version: 
NVIM v0.5.0
Build type: Release

Setting the path to nvim executable still crashes

**Comment by rohit-px2** [comment]
Alright, I'll have to take a look into what might be causing this.
One last question, was this happening before on older builds?

**Comment by en1tan** [comment]
no, I didn't build it but rather used the pre built binary

**Comment by rohit-px2** [comment]
Ok, was just wondering if it was an issue with the action build.

**Comment by kvietcong** [comment]
I have a similar issue but on Windows 10. However, it seems to work if I place NVUI within a folder that doesn't need admin privileges. So if I were to place it in Program Files, it would crash saying Nvui commands don't exist but if it's in a folder like my Downloads, it's all fine

**Comment by kvietcong** [comment]
On further testing, weirdly enough, it actually seems to not work when there is a space in the absolute path of the binary
