### ISSUE TITLE
Provide a fully-fledged release

### ISSUE THREAD

**Issue by anuvyklack** [rohit-px2/nvui#90]
I use [bin](https://github.com/marcosnils/bin) which allows installing and easy updating binary files from Github. But I cannot install `nvui` with it because there is no `releases/latest` page:

```
https://api.github.com/repos/rohit-px2/nvui/releases/latest
```

**Comment by rohit-px2** [comment]
Looks like if I remove the pre-release label it works properly. I added a new release but it might take a while for the actions to build it.

**Comment by anuvyklack** [comment]
Thank you very much! Great app!
