### ISSUE TITLE
Prevent closing the window if there are unsaved changes

### ISSUE THREAD

**Issue by silveste** [rohit-px2/nvui#92]
Is there any way to prevent the window close if we press the X window button and there are buffers not saved?

Ideally this could trigger a confirmation message before closing similar of `:conf qa<CR>`

**Comment by rohit-px2** [comment]
Yeah, it's possible if the close event is overridden and we can send a `confirm qa`, right now the spawned Neovim process just gets terminated so it quits without saving.

**Comment by silveste** [comment]
Yes, It works perfect

just for the record I tested in Manjaro (Arch)
