### ISSUE TITLE
How to enable features without external args?

### ISSUE THREAD

**Issue by huuson235** [rohit-px2/nvui#94]
I want to enable some features like external-cmd, external-popupmenu ... without passing args. How can I setup this in .vimrc.

**Comment by rohit-px2** [comment]
Right now it's not possible, I might add them soon.

**Comment by younger-1** [comment]
If you use `scoop`, you can install my personal [bucket](https://github.com/younger-1/scoop-it) and install `nvui` manifest which has configured these shims or shortcuts.

```
nvui --ext_multigrid
nvui --ext_multigrid --ext_popupmenu
nvui --ext_multigrid --ext_popupmenu --ext_cmdline
```

**Comment by rohit-px2** [comment]
So now you can toggle them using `:NvuiPopupmenu v:{true/false}` and `:NvuiCmdline`. I haven't added a release yet but you can find the builds [here](https://github.com/rohit-px2/nvui/actions/runs/1459236810).
