### ISSUE TITLE
numtab keys are not grabbed

### ISSUE THREAD

**Issue by gattomarcomix** [rohit-px2/nvui#95]
My keyboard layout is: it_IT.
In insert mode numeric all keys from numpad are ignored.
In normal mode too:
for example this vimrc configuration is affected:
`nmap  <Leader><k1>    <Leader>1`
`[<Leader>1]` is working
`[<Leader><k1>]` not

**Comment by rohit-px2** [comment]
Oops, didn't realize the keypad keys need to be prefixed with a k. Does #96 fix?

**Comment by gattomarcomix** [comment]
Problem fixed! I applied your patch from the numpad branch. Now the numpad works great.
