### ISSUE TITLE
[Questions]: cursor display problem

### ISSUE THREAD

**Issue by younger-1** [rohit-px2/nvui#97]
I have installed the newest release 0.2.0 on Windows 10. Everythings works fine except that the cursor is almost invisible. I have tried change colorscheme and cursor hightlighting but it didn't work. Is it possible to get the cursor to white or visible?

![b](https://user-images.githubusercontent.com/45989017/141922693-074793ac-e04b-4442-a947-0d5863a0a9fa.gif)

**Comment by rohit-px2** [comment]
Huh that's weird. If you haven't set a highlight group for the cursor using `guicursor` it should be using your default foreground color. Do you have `guicursor` set? If not could you show your `Normal` highlight group using `hi Normal`?

**Comment by younger-1** [comment]
I haven't set `guicursor` and it is nvim default value. 

And my highlight group:
```
:hi Normal
Normal         xxx ctermfg=145 ctermbg=235 guifg=#ABB2BF guibg=#282C34
```

**Comment by rohit-px2** [comment]
Okay, I'm getting the same error, I think I know what it is.

**Comment by younger-1** [comment]
Nice~

**Comment by rohit-px2** [comment]
Should be fixed now on main

**Comment by younger-1** [comment]
Thank you for your great work!
