### ISSUE TITLE
[feature request] file complete path on titlebar tooltip

### ISSUE THREAD

**Issue by gattomarcomix** [rohit-px2/nvui#99]
I often work on files with the same name in two nvui windows. It would be very useful to have a preview of the complete path to distinguish them more easily. Would it be possible to add a tooltip to the titlebar? Thank you.

**Comment by rohit-px2** [comment]
By complete path do you mean the full working directory/file path?
If you want to show the full file path then you can override `NvuiGetTitle` like so
```vim
" Put this somewhere in your init.vim
" Titlebar text will be something like "nvui • D:\Dev\file.txt"
function! NvuiGetTitle()
  return join(split("nvui," . expand("%:p"), ","), g:nvui_tb_separator)
endfunction
```

**Comment by gattomarcomix** [comment]
Thanks for the reply!
Yes, by complete path I mean just that.  
I followed your instructions and got the expected result.
This wil be a wonderful tip for the wiki!

WARNING!!! THE OVERRIDE MUST BE OUT OF BLOCK:
`if exists('g:nvui')
...
endif`

**Comment by rohit-px2** [comment]
Nice, I added it to the wiki as well.
